name: on-pr

on:
  pull_request:
    branches:
      - main
    types:
      - labeled
      - opened
      - reopened
      - synchronize
    paths:
      - '.github/workflows/on-pr.yaml'
      - '.gitops/**'
      - 'apis/**'
      - 'examples/**'
      - 'tests/**'
      - 'functions/**'
      - 'upbound.yaml'

permissions:
  packages: write
  contents: write
  issues: write
  pull-requests: write

jobs:
  validate:
    uses: unbounded-tech/workflows-crossplane/.github/workflows/validate.yaml@v2.0.0
    with:
      examples: |
        [
          { "example": "examples/podidentities/full-schema.yaml" },
          { "example": "examples/podidentities/example-minimal.yaml" }
        ]
      api_path: apis/podidentities
      error_on_missing_schemas: true

  test:
    uses: unbounded-tech/workflows-crossplane/.github/workflows/test.yaml@v2.0.0

  e2e:
    uses: unbounded-tech/workflows-crossplane/.github/workflows/e2e.yaml@v2.0.0
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    with:
      aws: true

  publish:
    needs:
      - validate
      - test
    uses: unbounded-tech/workflows-crossplane/.github/workflows/publish.yaml@v2.0.0
    secrets: inherit
    with:
      tag: pr-${{ github.event.pull_request.number }}-${{ github.sha }}
