name: on-push-main

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/on-push-main.yaml'
      - '.github/workflows/on-version-tagged.yaml'
      - '.gitops/**'
      - 'apis/**'
      - 'examples/**'
      - 'functions/**'
      - 'tests/**'
      - 'upbound.yaml'

permissions:
  packages: write
  contents: write
  issues: write
  pull-requests: write
  id-token: write  # Required for OIDC auth

jobs:
  validate:
    uses: unbounded-tech/workflows-crossplane/.github/workflows/validate.yaml@v2.12.2
    with:
      examples: |
        [
          { "example": "examples/podidentities/example-minimal.yaml" },
          { "example": "examples/podidentities/example-minimal.yaml", "observed_resources": "examples/test/mocks/observed-resources/minimal/steps/1/" },
          { "example": "examples/podidentities/example-minimal.yaml", "observed_resources": "examples/test/mocks/observed-resources/minimal/steps/2/" },
          { "example": "examples/podidentities/full-schema.yaml" },
          { "example": "examples/podidentities/full-schema.yaml", "observed_resources": "examples/test/mocks/observed-resources/full/steps/1/" },
          { "example": "examples/podidentities/full-schema.yaml", "observed_resources": "examples/test/mocks/observed-resources/full/steps/2/" }
        ]
      api_path: apis/podidentities
      error_on_missing_schemas: true

  test:
    uses: unbounded-tech/workflows-crossplane/.github/workflows/test.yaml@v2.12.2

  e2e:
    uses: unbounded-tech/workflows-crossplane/.github/workflows/e2e.yaml@v2.12.2
    with:
      aws: true
      aws-use-oidc: true
      aws-account-id: "034489662075"
      aws-region: us-east-2
      debug-resource-types: |
        [
          "networks.hops.ops.com.ai",
          "autoeksclusters.hops.ops.com.ai",
        ]
      timeout-minutes: 45
      cleanup-timeout-minutes: 45
  version-and-tag:
    name: Version and Tag
    needs:
      - validate
      - test
      - e2e
    uses: unbounded-tech/workflow-vnext-tag/.github/workflows/workflow.yaml@v1.20.2
    secrets:
      DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
    with:
      useDeployKey: true
      yqPatches: |
        patches:
          - filePath: .gitops/deploy/values.yaml
            selector: .version
            valuePrefix: "v"
          - filePath: .gitops/deploy/Chart.yaml
            selector: .version
            valuePrefix: ""
